"""Stable error vocabulary shared by runtime boundaries."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    UNSUPPORTED_TASK = "UNSUPPORTED_TASK"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_INVALID = "APPROVAL_INVALID"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVAL_ALREADY_USED = "APPROVAL_ALREADY_USED"
    AGENT_UNAVAILABLE = "AGENT_UNAVAILABLE"
    AGENT_TIMEOUT = "AGENT_TIMEOUT"
    AGENT_FAILED = "AGENT_FAILED"
    DEPENDENCY_FAILED = "DEPENDENCY_FAILED"
    SKILL_NOT_FOUND = "SKILL_NOT_FOUND"
    SKILL_TIMEOUT = "SKILL_TIMEOUT"
    SKILL_EXECUTION_ERROR = "SKILL_EXECUTION_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    OUTPUT_VALIDATION_ERROR = "OUTPUT_VALIDATION_ERROR"
    RETRIEVAL_ERROR = "RETRIEVAL_ERROR"
    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
    LLM_PROVIDER_ERROR = "LLM_PROVIDER_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    ALREADY_EXECUTED = "ALREADY_EXECUTED"
    MISSING_PRODUCT = "MISSING_PRODUCT"
    MISSING_SKU = "MISSING_SKU"
    MISSING_COMPETITOR = "MISSING_COMPETITOR"
    UNSUPPORTED_PLATFORM = "UNSUPPORTED_PLATFORM"
    UNSUPPORTED_REPORT_TYPE = "UNSUPPORTED_REPORT_TYPE"
    PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE"
    WORKFLOW_TIMEOUT = "WORKFLOW_TIMEOUT"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    SKILL_FAILED = "SKILL_FAILED"
    STEP_EXECUTION_ERROR = "STEP_EXECUTION_ERROR"
    GENERATION_ERROR = "GENERATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"


__all__ = ["ErrorCode"]
